### ISSUE TITLE
System.out.println()를 지양해야하는 이유

### ISSUE THREAD

**Issue by youngreal** [Stacked-Book/javaweb-nextstep-book-study#1]
3장에서 System.out.println()의 사용을 지양하고 로깅을 사용하자는 부분이 있습니다 
이는 많이 들어보셨을겁니다

그렇다면 System.out.println()이 성능에 좋지않은 이유는 무엇일까요? 
**왜 System.out.println()을 쓰면안되는걸까요?**
각자 공부해보시고 다음스터디에 랜덤으로 한분이 발표하게될 예정입니다 ㅎㅎ

**Comment by this-is-spear** [comment]
## **로깅 동작**

로그의 출력 동작은 단순합니다.

1. 로그 호출
    
    사용자는 원하는 로그를 출력하기 위해 해당 메서드를 출력합니다.
    
        
    <img width="701" alt="스크린샷 2022-07-27 오전 11 40 34" src="https://user-images.githubusercontent.com/92219795/181160728-32d46962-bd02-40ce-b3ee-1c4033c306f8.png">

    INFO 레벨의 로그를 출력하는 방법입니다.
    
    ```java
    log.info("this have message and {}", "params")
    ```
    
2. 필터로 검사
    
    필터를 통해 해당 로그가 유요한지 판단하게 됩니다.
    <img width="1111" alt="2" src="https://user-images.githubusercontent.com/92219795/181160870-323c0602-f6e3-4983-b8f0-12d7ac2c743b.png">

    INFO 레벨을 출력하게 된다면 들어가는 인자 값을 아래와 같습니다.
    
    ```java
    new LoggingEvent(FQCN, this, level, message, null, params)
    ```
    
3. 로깅 이벤트(`LoggingEvent`) 생성 및 어펜더(`Appender`)에 추가
    
    <img width="1141" alt="3" src="https://user-images.githubusercontent.com/92219795/181160902-c70b315e-5c1c-4733-855a-1b27c45eb105.png">
    
    **로깅 이벤트(`LoggingEvent`)**
    
    인자들을 가져와 로깅 이벤트 객체를 생성합니다. 해당 인자들은 어펜더(`Appender`)에 추가됩니다.
    
    <img width="959" alt="4" src="https://user-images.githubusercontent.com/92219795/181160917-c61a57be-f896-481c-bd02-615f655a8958.png">
    
    **어펜더(`Appender`)**
    
    Logback은 로그 이벤트를 wirte하는 작업을 Appender에게 위임합니다. 즉, Appender는로그 메세지가 출력될 대상을 결정하게 됩니다.
    
    <img width="760" alt="5" src="https://user-images.githubusercontent.com/92219795/181160925-d4c3cae7-b491-4c1a-82ad-d3fb31ce970a.png">

## **로깅의 이점**

### 1. println보다 성능상의 이점을 챙길 수 있다.

콘솔에서 출력하는 방식의 차이점에서 

무조건 실행되는 println 메서드의 특징때문에 메서드 내 모든 인자들은 문자열 연산이 됩니다.  한편 로깅에서는 상황별로 메시지를 남길 수 있기 때문에 실행되지 않는다면 문자열 연산이 되지 않습니다.  

```java
log.info("this have message and {}", "params")
```

중요한 점은 message 내부에 {} 포맷을 지정해 파라미터를 동적으로 삽입할 수 있는데 해당 로깅이 실행되지 않는다면 문자열 연산이 되지 않습니다. 해당 포맷을 사용하지 않고 덧셈 연산으로 메시지를 넘긴다면 println을 사용하는 것과 성능 차이가 없다는 것입니다.

### 2. Logger를 사용해 원하는 방식으로 출력(write)할 수 있습니다.

Logger는 예외의 스택 정보를 출력할 때 해당 클래스가 어떤 라이브러리를 참고하고 있는지도 포함하여 제공하기 때문에 쉽게 관련된 클래스를 확인할 수 있습니다. 그리고 Logger는 에러별, 상황별로 출력 할 수 있기 때문에 사용자가 원하는 방식으로 데이터를 출력(write)할 수 있습니다.

### 3. Console이 아닌 File에서도 데이터를 출력(write)할 수 있습니다.

println 메서드는 System.out을 이용해 콘솔에 문자열을 출력하는 기능이지만 로깅은 사용자가 원하는 방식으로 데이터를 출력(write)할 수 있습니다. Logger의 `ConsoleAppender`의 Appender를 이용해 로그를 콘솔에 System.out 또는 System.err를 이용하여 로그 이벤트를 append할 수 있고,  `FileAppender`의 Appender를 이용해 파일에 로그를 append할 수 있습니다. 추가적으로 RollingFileAppender을 사용하여 로그 파일을 rollover할 수 있습니다.

참고

[https://livenow14.tistory.com/64](https://livenow14.tistory.com/64)[경험의 연장선:티스토리]

**Comment by youngreal** [comment]
스터디시간에 다루어서 close하겠습니다
