### ISSUE TITLE
6장 issue(2) - 보안

### ISSUE THREAD

**Issue by youngreal** [Stacked-Book/javaweb-nextstep-book-study#7]
1. SQL인젝션이란? 발생원인과 대응방안
2. XSS? 발생원인과 대응방안
3. CSRF? 발생원인과 대응방안
4. 세션 하이재킹? 발생원인과 대응방안 

9/2 스터디시간에 이야기 나눠보는걸로 해보면 좋을것같습니다.

**Comment by itsjustsora** [comment]
1. SQL인젝션
   https://justsora.tistory.com/50
2. XSS
   https://justsora.tistory.com/51
3. CSRF
   https://justsora.tistory.com/52
4. 세션 하이재킹 (작성 중)
